<%
Dim IDS_TITLE, IDS_SELECT_DISPLAY, IDS_DISPLAY_BY_NAME, IDS_DISPLAY_BY_RESULT, IDS_DISPLAY_BY_DOWNLOAD_DATE, IDS_DISPLAY_BY_IP, IDS_DISPLAY_ALL
Dim IDS_USER_NAME, IDS_RESULT, IDS_DATE, IDS_IP_ADDRESS, IPS_SUCCESS, IDS_FAILURE, IDS_INCOMPLETE
Dim IDS_CN_USER_NAME, IDS_CN_REMOTE_HOST, IDS_CN_VERSION, IDS_CN_DOWNLOAD_REQ_TIME, IDS_CN_INSTALL_RESULT, IDS_CN_INSTALL_COMPLETE_TIME

IDS_TITLE = "패치 다운로드를 위한 Siebel 관리 페이지"
IDS_SELECT_DISPLAY = "아래에서 표시 스타일을 선택하십시오."
IDS_DISPLAY_BY_NAME = "이름별 표시"
IDS_DISPLAY_BY_RESULT = "결과별 표시"
IDS_DISPLAY_BY_DOWNLOAD_DATE = "다운로드 요청일별 표시"
IDS_DISPLAY_BY_IP = "IP 주소별 표시"
IDS_DISPLAY_ALL = "전체 표시"
IDS_USER_NAME = "사용자 이름:"
IDS_RESULT = "결과:"
IDS_DATE = "일자(년/월/일):"
IDS_IP_ADDRESS = "IP 주소:"
IDS_SUCCESS = "성공"
IDS_FAILURE = "실패"
IDS_INCOMPLETE = "InComplete"
IDS_SUBMIT = "전송"
IDS_ERR_RESULT_VALUE = "결과 값을 선택하십시오."
IDS_ERR_DATE_FORMAT = "년/월/일 형식으로 날짜를 입력하십시오."
IDS_ERR_IP_FORMAT = "IP 주소를 입력하십시오."
IDS_ERR_DISPLAY_STYLE = "표시 스타일을 선택하십시오."
IDS_CN_USER_NAME = "사용자 이름"
IDS_CN_REMOTE_HOST = "원격 호스트"
IDS_CN_VERSION = "버전"
IDS_CN_DOWNLOAD_REQ_TIME = "다운로드 요청 시간"
IDS_CN_INSTALL_RESULT = "설치 결과"
IDS_CN_INSTALL_COMPLETE_TIME = "설치 완료 시간"

%>