<%
Dim IDS_TITLE, IDS_SELECT_DISPLAY, IDS_DISPLAY_BY_NAME, IDS_DISPLAY_BY_RESULT, IDS_DISPLAY_BY_DOWNLOAD_DATE, IDS_DISPLAY_BY_IP, IDS_DISPLAY_ALL
Dim IDS_USER_NAME, IDS_RESULT, IDS_DATE, IDS_IP_ADDRESS, IPS_SUCCESS, IDS_FAILURE, IDS_INCOMPLETE
Dim IDS_CN_USER_NAME, IDS_CN_REMOTE_HOST, IDS_CN_VERSION, IDS_CN_DOWNLOAD_REQ_TIME, IDS_CN_INSTALL_RESULT, IDS_CN_INSTALL_COMPLETE_TIME

IDS_TITLE = "דף ניהול Siebel להורדת תיקון"
IDS_SELECT_DISPLAY = "בחר סגנון תצוגה מתוך האפשרויות להלן"
IDS_DISPLAY_BY_NAME = "תצוגה לפי שם"
IDS_DISPLAY_BY_RESULT = "תצוגה לפי תוצאה"
IDS_DISPLAY_BY_DOWNLOAD_DATE = "תצוגה לפי תאריך בקשת ההורדה"
IDS_DISPLAY_BY_IP = "תצוגה לפי כתובת IP"
IDS_DISPLAY_ALL = "תצוגת הכל"
IDS_USER_NAME = "שם משתמש:"
IDS_RESULT = "תוצאה:"
IDS_DATE = "תאריך (שנה/יום/חודש):"
IDS_IP_ADDRESS = "כתובת IP:"
IDS_SUCCESS = "הצלחה"
IDS_FAILURE = "כשל"
IDS_INCOMPLETE = "לא שלם"
IDS_SUBMIT = "הגש"
IDS_ERR_RESULT_VALUE = "בחר ערך תוצאה"
IDS_ERR_DATE_FORMAT = "הזן תאריך בתבנית שנה/יום/חודש"
IDS_ERR_IP_FORMAT = "הזן כתובת IP"
IDS_ERR_DISPLAY_STYLE = "בחר סגנון תצוגה"
IDS_CN_USER_NAME = "שם משתמש"
IDS_CN_REMOTE_HOST = "מארח מרוחק"
IDS_CN_VERSION = "גרסה"
IDS_CN_DOWNLOAD_REQ_TIME = "שעת בקשת ההורדה"
IDS_CN_INSTALL_RESULT = "תוצאת ההתקנה"
IDS_CN_INSTALL_COMPLETE_TIME = "שעת השלמת ההתקנה"

%>
