<%
Dim IDS_TITLE, IDS_SELECT_DISPLAY, IDS_DISPLAY_BY_NAME, IDS_DISPLAY_BY_RESULT, IDS_DISPLAY_BY_DOWNLOAD_DATE, IDS_DISPLAY_BY_IP, IDS_DISPLAY_ALL
Dim IDS_USER_NAME, IDS_RESULT, IDS_DATE, IDS_IP_ADDRESS, IPS_SUCCESS, IDS_FAILURE, IDS_INCOMPLETE
Dim IDS_CN_USER_NAME, IDS_CN_REMOTE_HOST, IDS_CN_VERSION, IDS_CN_DOWNLOAD_REQ_TIME, IDS_CN_INSTALL_RESULT, IDS_CN_INSTALL_COMPLETE_TIME

IDS_TITLE = "パッチダウンロード用 Siebel 管理ページ"
IDS_SELECT_DISPLAY = "表示形式を選択してください"
IDS_DISPLAY_BY_NAME = "名前を基に表示"
IDS_DISPLAY_BY_RESULT = "結果を基に表示"
IDS_DISPLAY_BY_DOWNLOAD_DATE = "ダウンロードリクエスト日付を基に表示"
IDS_DISPLAY_BY_IP = "IP アドレスを基に表示"
IDS_DISPLAY_ALL = "すべて表示"
IDS_USER_NAME = "ユーザー名 :"
IDS_RESULT = "結果 :"
IDS_DATE = "日付 (mm/dd/yyyy):"
IDS_IP_ADDRESS = "IP アドレス :"
IDS_SUCCESS = "成功"
IDS_FAILURE = "失敗"
IDS_INCOMPLETE = "未完了"
IDS_SUBMIT = "提出"
IDS_ERR_RESULT_VALUE = "結果の値を選択してください"
IDS_ERR_DATE_FORMAT = "日付を mm/dd/yyyy の形式で入力してください"
IDS_ERR_IP_FORMAT = "IP アドレスを入力してください"
IDS_ERR_DISPLAY_STYLE = "表示形式を選択してください"
IDS_CN_USER_NAME = "ユーザー名"
IDS_CN_REMOTE_HOST = "リモートホスト"
IDS_CN_VERSION = "バージョン"
IDS_CN_DOWNLOAD_REQ_TIME = "ダウンロードリクエスト時間"
IDS_CN_INSTALL_RESULT = "インストールの結果"
IDS_CN_INSTALL_COMPLETE_TIME = "インストール完了時間"

%>