<%
Dim IDS_TITLE, IDS_SELECT_DISPLAY, IDS_DISPLAY_BY_NAME, IDS_DISPLAY_BY_RESULT, IDS_DISPLAY_BY_DOWNLOAD_DATE, IDS_DISPLAY_BY_IP, IDS_DISPLAY_ALL
Dim IDS_USER_NAME, IDS_RESULT, IDS_DATE, IDS_IP_ADDRESS, IPS_SUCCESS, IDS_FAILURE, IDS_INCOMPLETE
Dim IDS_CN_USER_NAME, IDS_CN_REMOTE_HOST, IDS_CN_VERSION, IDS_CN_DOWNLOAD_REQ_TIME, IDS_CN_INSTALL_RESULT, IDS_CN_INSTALL_COMPLETE_TIME

IDS_TITLE = "Siebel 管理頁 (下載修正程式)"
IDS_SELECT_DISPLAY = "請在以下選擇顯示樣式"
IDS_DISPLAY_BY_NAME = "依名稱顯示"
IDS_DISPLAY_BY_RESULT = "依結果顯示"
IDS_DISPLAY_BY_DOWNLOAD_DATE = "依下載請求日期顯示"
IDS_DISPLAY_BY_IP = "依 IP 位址顯示"
IDS_DISPLAY_ALL = "全部顯示"
IDS_USER_NAME = "使用者名稱:"
IDS_RESULT = "結果:"
IDS_DATE = "日期 (mm/dd/yyyy):"
IDS_IP_ADDRESS = "IP 位址:"
IDS_SUCCESS = "成功"
IDS_FAILURE = "失敗"
IDS_INCOMPLETE = "不完整"
IDS_SUBMIT = "提交"
IDS_ERR_RESULT_VALUE = "請選擇結果值"
IDS_ERR_DATE_FORMAT = "請以 mm/dd/yyyy 格式輸入日期"
IDS_ERR_IP_FORMAT = "請輸入 IP 位址"
IDS_ERR_DISPLAY_STYLE = "請選擇顯示樣式"
IDS_CN_USER_NAME = "使用者名稱"
IDS_CN_REMOTE_HOST = "遠端主機"
IDS_CN_VERSION = "版本"
IDS_CN_DOWNLOAD_REQ_TIME = "下載請求時間"
IDS_CN_INSTALL_RESULT = "安裝結果"
IDS_CN_INSTALL_COMPLETE_TIME = "安裝完成時間"

%>