<%
Dim IDS_TITLE, IDS_SELECT_DISPLAY, IDS_DISPLAY_BY_NAME, IDS_DISPLAY_BY_RESULT, IDS_DISPLAY_BY_DOWNLOAD_DATE, IDS_DISPLAY_BY_IP, IDS_DISPLAY_ALL
Dim IDS_USER_NAME, IDS_RESULT, IDS_DATE, IDS_IP_ADDRESS, IPS_SUCCESS, IDS_FAILURE, IDS_INCOMPLETE
Dim IDS_CN_USER_NAME, IDS_CN_REMOTE_HOST, IDS_CN_VERSION, IDS_CN_DOWNLOAD_REQ_TIME, IDS_CN_INSTALL_RESULT, IDS_CN_INSTALL_COMPLETE_TIME

IDS_TITLE = "用于下载补丁的 Siebel 管理员页"
IDS_SELECT_DISPLAY = "请从下面选择一种显示样式。"
IDS_DISPLAY_BY_NAME = "按名称显示"
IDS_DISPLAY_BY_RESULT = "按结果显示"
IDS_DISPLAY_BY_DOWNLOAD_DATE = "按下载请求日期显示"
IDS_DISPLAY_BY_IP = "按 IP 地址显示"
IDS_DISPLAY_ALL = "全部显示"
IDS_USER_NAME = "用户名："
IDS_RESULT = "结果："
IDS_DATE = "日期 (mm/dd/yyyy)："
IDS_IP_ADDRESS = "IP 地址："
IDS_SUCCESS = "成功"
IDS_FAILURE = "失败"
IDS_INCOMPLETE = "未完成"
IDS_SUBMIT = "提交"
IDS_ERR_RESULT_VALUE = "请选择结果值"
IDS_ERR_DATE_FORMAT = "请以 mm/dd/yyyy 格式输入日期"
IDS_ERR_IP_FORMAT = "请输入 IP 地址"
IDS_ERR_DISPLAY_STYLE = "请选择显示样式"
IDS_CN_USER_NAME = "用户名"
IDS_CN_REMOTE_HOST = "远程主机"
IDS_CN_VERSION = "版本"
IDS_CN_DOWNLOAD_REQ_TIME = "下载请求时间"
IDS_CN_INSTALL_RESULT = "安装结果"
IDS_CN_INSTALL_COMPLETE_TIME = "安装结束时间"

%>